export const BADGE_CONFIG = {
  // ── Micro achievements (trigger frequently) ──
  first_checkin:     { label: 'First Step',         emoji: '👟', tier: 'bronze', desc: 'Completed first check-in',       auto: true },
  checkin_3:         { label: 'Getting Started',    emoji: '✅', tier: 'bronze', desc: '3 check-ins completed',           auto: true },
  checkin_5:         { label: 'Building Habits',    emoji: '📈', tier: 'bronze', desc: '5 check-ins completed',           auto: true },
  checkin_10:        { label: 'Double Digits',      emoji: '🔟', tier: 'silver', desc: '10 check-ins completed',          auto: true },
  first_meal_logged: { label: 'Fueled Up',          emoji: '🍽️', tier: 'bronze', desc: 'Logged first meal',               auto: true },
  meal_log_3days:    { label: 'Nutrition Tracking', emoji: '📊', tier: 'bronze', desc: 'Logged meals 3 days in a row',    auto: true },
  first_workout:     { label: 'First Sweat',        emoji: '🏋️', tier: 'bronze', desc: 'Completed first workout',         auto: true },
  workout_3:         { label: 'On a Roll',          emoji: '🎯', tier: 'bronze', desc: '3 workouts completed',            auto: true },
  weight_logged:     { label: 'Tracked It',         emoji: '⚖️', tier: 'bronze', desc: 'Logged body weight',              auto: true },
  sleep_7hrs:        { label: 'Well Rested',        emoji: '😴', tier: 'bronze', desc: 'Logged 7+ hours sleep',           auto: true },
  energy_high:       { label: 'Full Energy',        emoji: '⚡', tier: 'bronze', desc: 'Logged high energy day',          auto: true },
  mood_great:        { label: 'Great Mindset',      emoji: '😊', tier: 'bronze', desc: 'Logged great mood',               auto: true },
  compliance_80:     { label: 'Strong Week',        emoji: '💪', tier: 'bronze', desc: 'Hit 80% compliance',              auto: true },
  compliance_100:    { label: 'Perfect Day',        emoji: '🌟', tier: 'silver', desc: 'Hit 100% compliance',             auto: true },
  protein_hit:       { label: 'Protein Pro',        emoji: '🥩', tier: 'bronze', desc: 'Hit protein target',              auto: true },
  steps_10k:         { label: '10K Steps',          emoji: '🚶', tier: 'bronze', desc: 'Hit 10,000 steps',                auto: true },
  water_goal:        { label: 'Hydrated',           emoji: '💧', tier: 'bronze', desc: 'Hit water goal',                  auto: true },

  // ── Streaks ──
  streak_7:         { label: '7-Day Streak',     emoji: '🔥', tier: 'bronze',   desc: '7 consecutive check-ins' },
  streak_14:        { label: '14-Day Streak',     emoji: '⚡', tier: 'silver',   desc: '14 consecutive check-ins' },
  streak_30:        { label: '30-Day Streak',     emoji: '💎', tier: 'gold',     desc: '30-day champion' },
  streak_60:        { label: '60-Day Streak',     emoji: '👑', tier: 'platinum', desc: '60 days unstoppable' },
  streak_90:        { label: '90-Day Legend',     emoji: '🌟', tier: 'elite',    desc: '90 days of consistency' },

  // Performance
  pr_hit:           { label: 'PR Smashed',        emoji: '🏆', tier: 'gold',     desc: 'Personal record achieved' },
  first_checkin:    { label: 'First Step',        emoji: '👟', tier: 'bronze',   desc: 'Completed first check-in' },
  perfect_week:     { label: 'Perfect Week',      emoji: '⭐', tier: 'silver',   desc: '4 check-ins all 80%+' },
  perfect_month:    { label: 'Perfect Month',     emoji: '🎖️', tier: 'gold',     desc: 'Full month above 80%' },

  // Nutrition
  nutrition_king:   { label: 'Nutrition King',    emoji: '🥗', tier: 'silver',   desc: '14 days hitting macros' },
  macro_master:     { label: 'Macro Master',      emoji: '⚖️', tier: 'gold',     desc: '30 days hitting macros' },
  hydration_hero:   { label: 'Hydration Hero',    emoji: '💧', tier: 'bronze',   desc: 'Logged water 7 days straight' },

  // Transformation
  goal_reached:     { label: 'Goal Reached',      emoji: '🎯', tier: 'gold',     desc: 'Target achieved' },
  halfway_there:    { label: 'Halfway There',     emoji: '🏁', tier: 'silver',   desc: '50% of goal reached' },
  transformation:   { label: 'Transformation',   emoji: '🦋', tier: 'elite',    desc: 'Complete body transformation' },
  weight_loss_5:    { label: 'Lost 5 lbs',        emoji: '📉', tier: 'bronze',   desc: '5 lbs down' },
  weight_loss_10:   { label: 'Lost 10 lbs',       emoji: '🔽', tier: 'silver',   desc: '10 lbs down' },
  weight_loss_20:   { label: 'Lost 20 lbs',       emoji: '⬇️', tier: 'gold',     desc: '20 lbs down' },

  // Mental / Consistency
  comeback:         { label: 'Comeback Kid',      emoji: '💪', tier: 'silver',   desc: 'Bounced back strong' },
  consistent_month: { label: 'Iron Consistent',   emoji: '📅', tier: 'gold',     desc: '30 days of consistency' },
  mindset_warrior:  { label: 'Mindset Warrior',   emoji: '🧠', tier: 'silver',   desc: 'Logged mood 14 days' },
  early_bird:       { label: 'Early Bird',        emoji: '🌅', tier: 'bronze',   desc: 'Consistent morning training' },
  night_owl:        { label: 'Night Owl',         emoji: '🦉', tier: 'bronze',   desc: 'Consistent evening training' },
};

// Dark premium tier styles for cards
export const TIER_STYLES = {
  bronze: {
    bg:          '#3A2417',
    accent:      '#CD7F32',
    glow:        'rgba(205,127,50,0.35)',
    glowHover:   'rgba(205,127,50,0.6)',
    border:      'rgba(205,127,50,0.4)',
    text:        '#FFB870',
    label:       'Bronze',
    shimmer:     false,
    // legacy tailwind (used in small chips / BadgeRow)
    tw_bg:       'bg-[#FDF4EE]',
    tw_border:   'border-[#D97706]',
    tw_text:     'text-[#D97706]',
  },
  silver: {
    bg:          '#24262C',
    accent:      '#C0C0C0',
    glow:        'rgba(192,192,192,0.3)',
    glowHover:   'rgba(192,192,192,0.55)',
    border:      'rgba(192,192,192,0.35)',
    text:        '#E8E8E8',
    label:       'Silver',
    shimmer:     false,
    tw_bg:       'bg-[#F3F4F6]',
    tw_border:   'border-[#6B7280]',
    tw_text:     'text-[#6B7280]',
  },
  gold: {
    bg:          '#2C2414',
    accent:      '#FFD700',
    glow:        'rgba(255,215,0,0.3)',
    glowHover:   'rgba(255,215,0,0.6)',
    border:      'rgba(255,215,0,0.45)',
    text:        '#FFE566',
    label:       'Gold',
    shimmer:     false,
    tw_bg:       'bg-[#FFFBEB]',
    tw_border:   'border-[#D97706]',
    tw_text:     'text-[#D97706]',
  },
  platinum: {
    bg:          '#162530',
    accent:      '#62D7FF',
    glow:        'rgba(98,215,255,0.3)',
    glowHover:   'rgba(98,215,255,0.6)',
    border:      'rgba(98,215,255,0.4)',
    text:        '#A8EEFF',
    label:       'Platinum',
    shimmer:     false,
    tw_bg:       'bg-[#EFF6FF]',
    tw_border:   'border-[#2563EB]',
    tw_text:     'text-[#2563EB]',
  },
  elite: {
    bg:          '#0D0D14',
    accent:      '#2563EB',
    glow:        'rgba(37,99,235,0.4)',
    glowHover:   'rgba(120,60,255,0.7)',
    border:      'rgba(37,99,235,0.5)',
    text:        '#93C5FD',
    label:       'Elite',
    shimmer:     true,
    tw_bg:       'bg-[#111827]',
    tw_border:   'border-[#111827]',
    tw_text:     'text-white',
  },
};