// ─── SUPPLEMENTS ─────────────────────────────────────────────────────────────
export const SUPPLEMENTS = [
  // PERFORMANCE & MUSCLE
  {
    id: 'creatine',
    name: 'Creatine Monohydrate',
    category: 'Performance',
    dose: '5g daily — any time',
    timing: 'Any time, consistent daily use',
    what_it_does: 'Most researched supplement in existence. Increases ATP production, improves strength and power output, supports muscle retention during a cut, enhances cognitive function. Results visible within 2–4 weeks.',
    best_for: 'Everyone — male and female, cutting or bulking',
    stack_with: ['Carbs post-workout', 'Beta-Alanine'],
    avoid_with: [],
    rating: 'Essential',
  },
  {
    id: 'whey',
    name: 'Whey Protein',
    category: 'Performance',
    dose: '20–40g per serving, 1–2x daily',
    timing: 'Post-workout or between meals',
    what_it_does: 'Fast-absorbing complete protein. Supports muscle protein synthesis, hits daily protein targets, ideal post-workout or as a meal supplement.',
    best_for: 'Anyone struggling to hit protein targets through food alone',
    stack_with: ['Creatine', 'Carbohydrates'],
    avoid_with: [],
    rating: 'Essential',
  },
  {
    id: 'beta-alanine',
    name: 'Beta-Alanine',
    category: 'Performance',
    dose: '3.2–6.4g daily',
    timing: 'Pre-workout or split throughout day',
    what_it_does: 'Buffers lactic acid buildup in muscles, delays fatigue during high-rep or high-intensity training. Causes harmless tingling (paresthesia) when first starting.',
    best_for: 'Endurance athletes, CrossFit, high rep training',
    stack_with: ['Creatine', 'Caffeine'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'caffeine',
    name: 'Caffeine',
    category: 'Performance',
    dose: '100–200mg, 30–45 min pre-workout',
    timing: '30–45 min before training',
    what_it_does: 'Increases adrenaline, improves focus, reduces perceived effort, enhances endurance and strength performance. Most effective pre-workout ingredient.',
    best_for: 'Morning or afternoon training',
    stack_with: ['L-Theanine (2:1 ratio)', 'L-Citrulline'],
    avoid_with: ['Within 6 hours of sleep'],
    rating: 'Recommended',
  },
  {
    id: 'l-citrulline',
    name: 'L-Citrulline',
    category: 'Performance',
    dose: '6–8g, 30–60 min pre-workout',
    timing: '30–60 min before training',
    what_it_does: 'Converts to arginine in the kidneys, increases nitric oxide production, delivers better pumps, improves blood flow and endurance. Superior to arginine supplementation.',
    best_for: 'Anyone wanting better pumps and endurance',
    stack_with: ['Caffeine', 'Beta-Alanine'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'pre-workout',
    name: 'Pre-Workout (stim based)',
    category: 'Performance',
    dose: '1 serving 20–30 min before training',
    timing: '20–30 min pre-workout',
    what_it_does: 'Combination of caffeine, citrulline, beta-alanine, and focus compounds for energy, pumps, and performance.',
    best_for: 'Low energy training days',
    stack_with: [],
    avoid_with: ['Late night training'],
    rating: 'Optional',
  },
  // RECOVERY
  {
    id: 'omega3',
    name: 'Omega-3 Fish Oil',
    category: 'Recovery',
    dose: '2–3g EPA+DHA daily with food',
    timing: 'With any meal',
    what_it_does: 'Reduces systemic inflammation, supports joint health and mobility, improves brain function, supports heart health, enhances fat oxidation. One of the most impactful daily supplements.',
    best_for: 'Everyone — especially high volume training',
    stack_with: ['Vitamin D3', 'Vitamin E'],
    avoid_with: [],
    rating: 'Essential',
  },
  {
    id: 'magnesium',
    name: 'Magnesium Glycinate',
    category: 'Recovery',
    dose: '200–400mg before bed',
    timing: '30–60 min before sleep',
    what_it_does: 'Most bioavailable form of magnesium. Supports muscle relaxation and recovery, improves deep sleep quality, reduces cortisol, supports gut motility, and reduces stress. Over 70% of people are deficient.',
    best_for: 'Anyone with poor sleep, high stress, or muscle cramps',
    stack_with: ['Glycine', 'Ashwagandha'],
    avoid_with: [],
    rating: 'Essential',
  },
  {
    id: 'tart-cherry',
    name: 'Tart Cherry Extract',
    category: 'Recovery',
    dose: '480mg, twice daily',
    timing: 'Morning and evening with food',
    what_it_does: 'Powerful natural anti-inflammatory. Reduces muscle soreness and DOMS, accelerates recovery between sessions, improves sleep quality due to natural melatonin content.',
    best_for: 'High frequency training, athletes, anyone with soreness issues',
    stack_with: ['Omega-3', 'Collagen Peptides'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'collagen',
    name: 'Collagen Peptides',
    category: 'Recovery',
    dose: '10–15g daily, ideally with Vitamin C',
    timing: 'Morning or pre-workout with Vitamin C',
    what_it_does: 'Supports joint, tendon, and ligament health. Reduces joint pain, improves skin elasticity, supports gut lining integrity. Take with Vitamin C for maximum absorption.',
    best_for: 'Anyone with joint issues, over 30, high impact training',
    stack_with: ['Vitamin C'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'glutamine',
    name: 'L-Glutamine',
    category: 'Recovery',
    dose: '5–10g post-workout or before bed',
    timing: 'Post-workout or before bed',
    what_it_does: 'Most abundant amino acid in muscle tissue. Supports gut health and immune function, reduces muscle breakdown during caloric deficit, accelerates recovery.',
    best_for: 'Cutting phases, high stress, gut issues',
    stack_with: ['Whey Protein', 'Probiotics'],
    avoid_with: [],
    rating: 'Optional',
  },
  // HORMONES & TESTOSTERONE
  {
    id: 'zinc',
    name: 'Zinc',
    category: 'Hormones',
    dose: '15–30mg before bed with food',
    timing: 'Before bed with food',
    what_it_does: 'Essential mineral for testosterone production, immune function, protein synthesis, and wound healing. Deficiency is extremely common, especially in athletes who sweat heavily.',
    best_for: 'Men, athletes, anyone with low testosterone',
    stack_with: ['Magnesium Glycinate', 'Vitamin D3'],
    avoid_with: ['Empty stomach'],
    rating: 'Essential',
  },
  {
    id: 'vitamin-d3-k2',
    name: 'Vitamin D3 + K2',
    category: 'Hormones',
    dose: '2,000–5,000 IU D3 + 100mcg K2',
    timing: 'With fat-containing meal',
    what_it_does: 'D3 supports testosterone production, immune function, bone density, mood, and fat loss. K2 directs calcium to bones instead of arteries. Over 80% of people are deficient in D3.',
    best_for: 'Everyone — especially those with limited sun exposure',
    stack_with: ['Omega-3', 'Magnesium'],
    avoid_with: [],
    rating: 'Essential',
  },
  {
    id: 'ashwagandha',
    name: 'Ashwagandha (KSM-66)',
    category: 'Hormones',
    dose: '300–600mg before bed',
    timing: 'Before bed',
    what_it_does: 'Adaptogenic herb that significantly reduces cortisol levels, supports testosterone and luteinizing hormone, improves sleep quality, reduces anxiety, enhances recovery. KSM-66 is the most studied form.',
    best_for: 'High stress, poor sleep, low testosterone, overtraining',
    stack_with: ['Magnesium Glycinate', 'Zinc'],
    avoid_with: [],
    rating: 'Essential',
  },
  {
    id: 'tongkat-ali',
    name: 'Tongkat Ali (Longjack)',
    category: 'Hormones',
    dose: '200–400mg daily',
    timing: 'Morning with food',
    what_it_does: 'Increases free testosterone by reducing SHBG, improves libido and sexual health, reduces cortisol, enhances muscle building response. Combines well with Ashwagandha.',
    best_for: 'Men over 30, anyone with low testosterone or high stress',
    stack_with: ['Ashwagandha', 'Zinc'],
    avoid_with: [],
    rating: 'Advanced',
  },
  {
    id: 'fadogia',
    name: 'Fadogia Agrestis',
    category: 'Hormones',
    dose: '425–600mg daily',
    timing: 'Morning with food — cycle 8 weeks on, 4 weeks off',
    what_it_does: 'Increases LH (luteinizing hormone) which signals testosterone production. Popular in testosterone optimization stacks. Less research than other compounds — cycle 8 weeks on, 4 weeks off.',
    best_for: 'Men focused on testosterone optimization',
    stack_with: ['Tongkat Ali', 'Zinc'],
    avoid_with: [],
    rating: 'Advanced',
  },
  // FAT LOSS
  {
    id: 'l-carnitine',
    name: 'L-Carnitine',
    category: 'Fat Loss',
    dose: '1–2g daily, with carbs',
    timing: 'With carbohydrate-containing meal',
    what_it_does: 'Transports fatty acids into mitochondria for energy production. Enhances fat oxidation, improves recovery, and reduces muscle damage. Most effective when taken with carbohydrates.',
    best_for: 'Fat loss phases, endurance training, body recomposition',
    stack_with: ['Caffeine', 'Green Tea Extract'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'green-tea',
    name: 'Green Tea Extract (EGCG)',
    category: 'Fat Loss',
    dose: '400–500mg daily',
    timing: 'Morning with food',
    what_it_does: 'Increases metabolism through thermogenesis, enhances fat oxidation, powerful antioxidant. Works synergistically with caffeine. Contains L-theanine which reduces caffeine jitters.',
    best_for: 'Fat loss phases, anyone wanting metabolic support',
    stack_with: ['Caffeine', 'L-Carnitine'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'berberine',
    name: 'Berberine',
    category: 'Fat Loss',
    dose: '500mg, 2–3x daily with meals',
    timing: 'With each main meal',
    what_it_does: 'Activates AMPK (same pathway as Metformin), improves insulin sensitivity, reduces blood glucose, supports fat loss and metabolic health. Often called nature\'s Ozempic.',
    best_for: 'Anyone with blood sugar issues, insulin resistance, fat loss',
    stack_with: ['Omega-3', 'Chromium'],
    avoid_with: ['Blood sugar medications'],
    rating: 'Advanced',
  },
  // BRAIN & FOCUS
  {
    id: 'lions-mane',
    name: "Lion's Mane Mushroom",
    category: 'Brain',
    dose: '500–1,000mg daily',
    timing: 'Morning with food',
    what_it_does: 'Stimulates NGF (nerve growth factor), enhances memory and cognitive function, reduces brain fog, supports neuroplasticity, has neuroprotective properties. Effects build over weeks.',
    best_for: 'Mental performance, focus, anyone with brain fog',
    stack_with: ['Alpha GPC', 'L-Theanine'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'l-theanine',
    name: 'L-Theanine',
    category: 'Brain',
    dose: '100–200mg, alone or with caffeine',
    timing: 'With caffeine or before bed',
    what_it_does: 'Promotes calm focus without sedation, reduces anxiety and jitters from caffeine, improves sleep quality, enhances alpha brain wave activity.',
    best_for: 'Anyone with anxiety, caffeine sensitivity, stress',
    stack_with: ['Caffeine (2:1 ratio)'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'alpha-gpc',
    name: 'Alpha GPC',
    category: 'Brain',
    dose: '300–600mg before training or work',
    timing: 'Pre-workout or morning',
    what_it_does: 'Precursor to acetylcholine (the learning neurotransmitter), enhances focus, memory, and mind-muscle connection, also shown to increase growth hormone release.',
    best_for: 'Mental performance, pre-workout focus, athletes',
    stack_with: ["Lion's Mane", 'Caffeine'],
    avoid_with: [],
    rating: 'Optional',
  },
  // SLEEP
  {
    id: 'melatonin',
    name: 'Melatonin',
    category: 'Sleep',
    dose: '0.5–3mg, 30–60 min before bed',
    timing: '30–60 min before sleep',
    what_it_does: 'Regulates circadian rhythm, signals the body to prepare for sleep. Lower doses (0.5–1mg) are more effective than high doses for most people.',
    best_for: 'Jet lag, shift workers, irregular sleep schedules',
    stack_with: ['Magnesium Glycinate', 'L-Theanine'],
    avoid_with: ['Nightly long-term use — not for chronic use'],
    rating: 'Optional',
  },
  {
    id: 'glycine',
    name: 'Glycine',
    category: 'Sleep',
    dose: '3–5g before bed',
    timing: 'Before bed',
    what_it_does: 'Improves sleep quality, reduces core body temperature for better sleep onset, supports collagen production, and has calming effects on the nervous system.',
    best_for: 'Anyone wanting deeper sleep',
    stack_with: ['Magnesium Glycinate', 'Ashwagandha'],
    avoid_with: [],
    rating: 'Recommended',
  },
  // GUT HEALTH
  {
    id: 'probiotic',
    name: 'Probiotic (multi-strain)',
    category: 'Gut',
    dose: '10–50 billion CFU daily',
    timing: 'Morning on empty stomach or with food',
    what_it_does: 'Supports gut microbiome diversity, improves digestion, enhances immune function, reduces bloating, improves nutrient absorption.',
    best_for: 'Anyone with digestive issues, after antibiotics, immune support',
    stack_with: ['L-Glutamine', 'Digestive Enzymes'],
    avoid_with: [],
    rating: 'Recommended',
  },
  {
    id: 'digestive-enzymes',
    name: 'Digestive Enzymes',
    category: 'Gut',
    dose: '1–2 capsules with main meals',
    timing: 'At start of each main meal',
    what_it_does: 'Breaks down proteins, fats, and carbohydrates more efficiently, reduces bloating and gas, improves nutrient absorption, especially helpful when eating high protein diets.',
    best_for: 'High protein intake, digestive discomfort, bloating',
    stack_with: ['Probiotics', 'L-Glutamine'],
    avoid_with: [],
    rating: 'Optional',
  },
];

export const SUPPLEMENT_CATEGORIES = ['All', 'Performance', 'Recovery', 'Hormones', 'Fat Loss', 'Brain', 'Sleep', 'Gut'];

export const SUPPLEMENT_RATINGS = ['Essential', 'Recommended', 'Optional', 'Advanced'];

export const SUPPLEMENT_RATING_COLORS = {
  Essential:    { bg: 'bg-emerald-100', text: 'text-emerald-700' },
  Recommended:  { bg: 'bg-blue-100',    text: 'text-blue-700' },
  Optional:     { bg: 'bg-slate-100',   text: 'text-slate-600' },
  Advanced:     { bg: 'bg-purple-100',  text: 'text-purple-700' },
};

export const SUPPLEMENT_CATEGORY_COLORS = {
  Performance: { bg: 'bg-orange-100', text: 'text-orange-700' },
  Recovery:    { bg: 'bg-blue-100',   text: 'text-blue-700' },
  Hormones:    { bg: 'bg-purple-100', text: 'text-purple-700' },
  'Fat Loss':  { bg: 'bg-rose-100',   text: 'text-rose-700' },
  Brain:       { bg: 'bg-cyan-100',   text: 'text-cyan-700' },
  Sleep:       { bg: 'bg-indigo-100', text: 'text-indigo-700' },
  Gut:         { bg: 'bg-green-100',  text: 'text-green-700' },
};

// ─── VITAMINS ─────────────────────────────────────────────────────────────────
export const VITAMINS = [
  // FAT-SOLUBLE
  { id: 'vit-a', name: 'Vitamin A (Retinol)', type: 'Fat-Soluble', rda: '700–900mcg RAE', upper: '3,000mcg', what_it_does: 'Vision (especially night vision), immune function, skin health, cell growth and reproduction.', deficiency: 'Night blindness, impaired immunity, dry skin.', sources: 'Liver, egg yolks, dairy, orange/yellow vegetables', at_risk: 'Low fat diet, gut issues', timing: 'With fat-containing meal', with_food: true },
  { id: 'vit-d3', name: 'Vitamin D3', type: 'Fat-Soluble', rda: '600–800 IU (optimal: 2,000–5,000 IU)', upper: '10,000 IU', what_it_does: 'Calcium absorption, bone density, immune function, testosterone production, mood regulation, reduces inflammation.', deficiency: 'Weak bones, low testosterone, depression, impaired immunity.', sources: 'Sunlight, fatty fish, egg yolks, fortified foods', at_risk: '80% of people — limited sun, dark skin, indoor lifestyle', timing: 'With fat-containing meal + K2', with_food: true },
  { id: 'vit-e', name: 'Vitamin E', type: 'Fat-Soluble', rda: '15mg', upper: '1,000mg', what_it_does: 'Powerful antioxidant, immune function, skin health, protects cells from oxidative damage, supports heart health.', deficiency: 'Muscle weakness, immune problems, nerve damage.', sources: 'Nuts, seeds, vegetable oils', at_risk: 'Low fat dieters', timing: 'With fat-containing meal', with_food: true },
  { id: 'vit-k2', name: 'Vitamin K2 (MK-7)', type: 'Fat-Soluble', rda: '90–120mcg', upper: 'No established limit', what_it_does: 'Directs calcium to bones instead of arteries, supports cardiovascular health, bone density, works synergistically with D3.', deficiency: 'Arterial calcification, weak bones.', sources: 'Natto, hard cheeses, liver', at_risk: 'Anyone supplementing D3', timing: 'With D3 and fat-containing meal', with_food: true },
  // WATER-SOLUBLE
  { id: 'vit-c', name: 'Vitamin C', type: 'Water-Soluble', rda: '75–90mg (optimal: 500–1,000mg)', upper: '2,000mg', what_it_does: 'Immune function, collagen synthesis, antioxidant, iron absorption, wound healing, stress response.', deficiency: 'Scurvy, impaired immunity, poor wound healing.', sources: 'Citrus, bell peppers, strawberries, broccoli', at_risk: 'Smokers, high stress individuals', timing: 'Morning with breakfast', with_food: true },
  { id: 'vit-b1', name: 'Vitamin B1 (Thiamine)', type: 'Water-Soluble', rda: '1.1–1.2mg', upper: 'No established limit', what_it_does: 'Energy metabolism, nervous system function, converts carbohydrates to energy.', deficiency: 'Fatigue, nerve damage, heart problems.', sources: 'Whole grains, legumes, pork', at_risk: 'Alcohol users, low carb dieters', timing: 'With food', with_food: true },
  { id: 'vit-b2', name: 'Vitamin B2 (Riboflavin)', type: 'Water-Soluble', rda: '1.1–1.3mg', upper: 'No established limit', what_it_does: 'Energy production, antioxidant, fat metabolism, converts B6 and folate to active forms.', deficiency: 'Fatigue, skin issues, cracked lips, eye sensitivity.', sources: 'Dairy, eggs, lean meats, leafy greens', at_risk: 'Vegans, athletes', timing: 'With food', with_food: true },
  { id: 'vit-b3', name: 'Vitamin B3 (Niacin)', type: 'Water-Soluble', rda: '14–16mg', upper: '35mg', what_it_does: 'Energy metabolism, DNA repair, cholesterol management, skin health. High doses may cause skin flushing.', deficiency: 'Pellagra, fatigue, skin rash.', sources: 'Meat, poultry, fish, peanuts', at_risk: 'Corn-based diet populations', timing: 'With food', with_food: true },
  { id: 'vit-b5', name: 'Vitamin B5 (Pantothenic Acid)', type: 'Water-Soluble', rda: '5mg', upper: 'No established limit', what_it_does: 'Coenzyme A synthesis, energy metabolism, hormone production, wound healing.', deficiency: 'Rare — fatigue, numbness, irritability.', sources: 'Widespread in foods — meat, avocado, eggs', at_risk: 'Malnutrition only', timing: 'With food', with_food: true },
  { id: 'vit-b6', name: 'Vitamin B6 (Pyridoxine)', type: 'Water-Soluble', rda: '1.3–1.7mg', upper: '100mg', what_it_does: 'Protein metabolism, neurotransmitter synthesis (serotonin, dopamine), immune function, hormone regulation.', deficiency: 'Depression, confusion, weak immunity.', sources: 'Poultry, fish, potatoes, non-citrus fruits', at_risk: 'Athletes, high protein dieters', timing: 'With food', with_food: true },
  { id: 'vit-b7', name: 'Vitamin B7 (Biotin)', type: 'Water-Soluble', rda: '30mcg', upper: 'No established limit', what_it_does: 'Fatty acid synthesis, amino acid metabolism, hair and nail health, blood sugar regulation.', deficiency: 'Hair loss, brittle nails, fatigue.', sources: 'Eggs (especially yolk), liver, nuts', at_risk: 'Raw egg white consumers', timing: 'With food', with_food: true },
  { id: 'vit-b9', name: 'Vitamin B9 (Folate)', type: 'Water-Soluble', rda: '400mcg', upper: '1,000mcg', what_it_does: 'DNA synthesis, cell division, red blood cell formation, critical during pregnancy.', deficiency: 'Anemia, neural tube defects, fatigue.', sources: 'Leafy greens, legumes, fortified grains', at_risk: 'Pregnant women, alcohol users', timing: 'With food', with_food: true },
  { id: 'vit-b12', name: 'Vitamin B12', type: 'Water-Soluble', rda: '2.4mcg', upper: 'No established limit', what_it_does: 'Red blood cell formation, neurological function, DNA synthesis, energy metabolism.', deficiency: 'Anemia, nerve damage, fatigue, cognitive decline.', sources: 'Meat, fish, dairy, eggs', at_risk: 'Vegans/vegetarians, over 50, gut issues (requires intrinsic factor)', timing: 'Morning with food', with_food: true },
  // MINERALS
  { id: 'calcium', name: 'Calcium', type: 'Mineral', rda: '1,000–1,200mg', upper: '2,500mg', what_it_does: 'Bone and teeth strength, muscle contraction, nerve signaling, blood clotting.', deficiency: 'Osteoporosis, muscle cramps, nerve problems.', sources: 'Dairy, leafy greens, fortified foods', at_risk: 'Low dairy intake, post-menopausal women', timing: 'Spread throughout day', with_food: true },
  { id: 'iron', name: 'Iron', type: 'Mineral', rda: '8mg men / 18mg women', upper: '45mg', what_it_does: 'Oxygen transport in blood, energy metabolism, immune function.', deficiency: 'Anemia, fatigue, impaired performance.', sources: 'Red meat, poultry, fish, legumes, fortified cereals', at_risk: 'Women, endurance athletes, vegans', timing: 'With Vitamin C for absorption, away from calcium', with_food: true },
  { id: 'magnesium-min', name: 'Magnesium', type: 'Mineral', rda: '310–420mg', upper: '350mg from supplements', what_it_does: '300+ enzymatic reactions, muscle and nerve function, blood sugar regulation, protein synthesis, sleep. Best forms: Glycinate for sleep/stress, Malate for energy, Citrate for gut.', deficiency: 'Muscle cramps, poor sleep, anxiety, constipation.', sources: 'Leafy greens, nuts, seeds, dark chocolate', at_risk: '70% of people', timing: 'Before bed (Glycinate) or with food', with_food: true },
  { id: 'zinc-min', name: 'Zinc', type: 'Mineral', rda: '8–11mg', upper: '40mg', what_it_does: 'Immune function, testosterone production, protein synthesis, wound healing, taste and smell.', deficiency: 'Low testosterone, impaired immunity, hair loss.', sources: 'Oysters, beef, seeds, legumes', at_risk: 'Athletes, men, vegans', timing: 'Before bed with food', with_food: true },
  { id: 'selenium', name: 'Selenium', type: 'Mineral', rda: '55mcg', upper: '400mcg', what_it_does: 'Antioxidant, thyroid function, DNA synthesis, immune function. 2 Brazil nuts = full daily dose.', deficiency: 'Thyroid issues, impaired immunity, infertility.', sources: '2 Brazil nuts daily, seafood, meats', at_risk: 'Low soil selenium regions', timing: 'With food', with_food: true },
  { id: 'iodine', name: 'Iodine', type: 'Mineral', rda: '150mcg', upper: '1,100mcg', what_it_does: 'Thyroid hormone production, metabolism regulation, brain development.', deficiency: 'Hypothyroidism, fatigue, weight gain.', sources: 'Iodized salt, seafood, dairy', at_risk: 'Low salt diets, inland regions', timing: 'With food', with_food: true },
  { id: 'chromium', name: 'Chromium', type: 'Mineral', rda: '25–35mcg', upper: 'No established limit', what_it_does: 'Enhances insulin sensitivity, blood sugar regulation, carbohydrate metabolism.', deficiency: 'Impaired blood sugar control.', sources: 'Broccoli, beef, whole grains', at_risk: 'Insulin resistance, high sugar diets', timing: 'With meals', with_food: true },
  // ELECTROLYTES
  { id: 'sodium', name: 'Sodium', type: 'Electrolyte', rda: '1,500–2,300mg', upper: '2,300mg', what_it_does: 'Fluid balance, nerve function, muscle contraction. Athletes need more — especially in heat or heavy sweating.', deficiency: 'Muscle cramps, fatigue, headaches, poor performance.', sources: 'Table salt, processed foods, electrolyte drinks', at_risk: 'Endurance athletes, heavy sweaters', timing: 'Throughout day — more on training days', with_food: false },
  { id: 'potassium', name: 'Potassium', type: 'Electrolyte', rda: '2,600–3,400mg', upper: 'No supplement limit set', what_it_does: 'Heart function, muscle contraction, fluid balance, blood pressure regulation.', deficiency: 'Muscle cramps, weakness, irregular heartbeat.', sources: 'Bananas, potatoes, avocado, leafy greens', at_risk: 'Low fruit/veggie intake, athletes', timing: 'Throughout day from food', with_food: false },
  { id: 'electrolyte-packets', name: 'Electrolyte Packets (LMNT / Liquid IV)', type: 'Electrolyte', rda: '1–2 packets daily', upper: 'Adjust to sweat levels', what_it_does: 'Replaces sodium, potassium, and magnesium lost in sweat. Improves hydration, performance, pumps, and recovery.', deficiency: 'Cramping, poor performance, fatigue during exercise.', sources: 'Supplement — LMNT, Liquid IV, Nuun', at_risk: 'Athletes, heavy sweaters, keto dieters', timing: 'Pre-workout or morning', with_food: false },
];

export const VITAMIN_TYPES = ['All', 'Fat-Soluble', 'Water-Soluble', 'Mineral', 'Electrolyte'];

export const VITAMIN_TYPE_COLORS = {
  'Fat-Soluble':  { bg: 'bg-amber-100',  text: 'text-amber-700' },
  'Water-Soluble':{ bg: 'bg-blue-100',   text: 'text-blue-700' },
  Mineral:        { bg: 'bg-slate-100',  text: 'text-slate-700' },
  Electrolyte:    { bg: 'bg-cyan-100',   text: 'text-cyan-700' },
};

// ─── SAUCES ───────────────────────────────────────────────────────────────────
export const SAUCES = [
  // ZERO CALORIE
  { id: 's1', name: 'Hot Sauce (Cholula, Tabasco, Frank\'s)', calories: '0', serving: 'per tsp', macros: '0g P / 0g C / 0g F', best_with: ['Eggs', 'Chicken', 'Fish', 'Rice'], flavor: ['Spicy', 'Tangy'], tier: 'Zero Cal' },
  { id: 's2', name: 'Mustard (yellow, Dijon, spicy brown)', calories: '5', serving: 'per tsp', macros: '0g P / 0g C / 0g F', best_with: ['Chicken', 'Beef', 'Sandwiches', 'Dressings'], flavor: ['Tangy', 'Sharp'], tier: 'Zero Cal' },
  { id: 's3', name: 'Lite Soy Sauce', calories: '10', serving: 'per tbsp', macros: '1g P / 1g C / 0g F', best_with: ['Rice', 'Stir Fry', 'Fish', 'Chicken'], flavor: ['Umami', 'Salty'], tier: 'Zero Cal' },
  { id: 's4', name: 'Coconut Aminos', calories: '10', serving: 'per tbsp', macros: '0g P / 2g C / 0g F', best_with: ['Stir Fry', 'Rice', 'Vegetables'], flavor: ['Umami', 'Slightly Sweet'], tier: 'Zero Cal' },
  { id: 's5', name: 'Apple Cider Vinegar', calories: '0', serving: 'per tbsp', macros: '0g P / 0g C / 0g F', best_with: ['Dressings', 'Marinades', 'Sauces'], flavor: ['Tart', 'Sharp'], tier: 'Zero Cal' },
  { id: 's6', name: 'Lemon Juice', calories: '5', serving: 'per oz', macros: '0g P / 1g C / 0g F', best_with: ['Fish', 'Chicken', 'Salads', 'Vegetables'], flavor: ['Bright', 'Citrusy'], tier: 'Zero Cal' },
  { id: 's7', name: 'Lime Juice', calories: '5', serving: 'per oz', macros: '0g P / 1g C / 0g F', best_with: ['Fish', 'Mexican', 'Salads'], flavor: ['Bright', 'Citrusy'], tier: 'Zero Cal' },
  { id: 's8', name: 'Worcestershire Sauce (low sodium)', calories: '5', serving: 'per tsp', macros: '0g P / 1g C / 0g F', best_with: ['Beef', 'Marinades', 'Soups'], flavor: ['Umami', 'Complex'], tier: 'Zero Cal' },
  // LOW CALORIE
  { id: 's9', name: 'Salsa (fresh or jarred)', calories: '10', serving: 'per 2 tbsp', macros: '0g P / 2g C / 0g F', best_with: ['Eggs', 'Chicken', 'Ground Beef', 'Fish'], flavor: ['Fresh', 'Spicy', 'Tangy'], tier: 'Low Cal' },
  { id: 's10', name: 'Sugar-Free Ketchup', calories: '5', serving: 'per tbsp', macros: '0g P / 1g C / 0g F', best_with: ['Eggs', 'Turkey Burger', 'Sweet Potato'], flavor: ['Sweet', 'Tangy'], tier: 'Low Cal' },
  { id: 's11', name: 'Sriracha', calories: '5', serving: 'per tsp', macros: '0g P / 1g C / 0g F', best_with: ['Eggs', 'Rice', 'Noodles', 'Chicken'], flavor: ['Spicy', 'Garlicky', 'Tangy'], tier: 'Low Cal' },
  { id: 's12', name: 'Sambal Oelek', calories: '5', serving: 'per tsp', macros: '0g P / 1g C / 0g F', best_with: ['Stir Fry', 'Rice', 'Soups'], flavor: ['Spicy', 'Pure Chili'], tier: 'Low Cal' },
  { id: 's13', name: 'Fish Sauce', calories: '5', serving: 'per tsp', macros: '1g P / 0g C / 0g F', best_with: ['Thai dishes', 'Stir Fry', 'Marinades'], flavor: ['Umami', 'Salty', 'Funky'], tier: 'Low Cal' },
  { id: 's14', name: 'Harissa Paste', calories: '15', serving: 'per tsp', macros: '0g P / 1g C / 1g F', best_with: ['Chicken', 'Lamb', 'Eggs', 'Hummus'], flavor: ['Spicy', 'Smoky', 'Complex'], tier: 'Low Cal' },
  { id: 's15', name: 'Greek Yogurt Sauce', calories: '20', serving: 'per 2 tbsp', macros: '3g P / 1g C / 0g F', best_with: ['Chicken', 'Fish', 'Wraps', 'Vegetables'], flavor: ['Tangy', 'Creamy'], tier: 'Low Cal' },
  // MODERATE CALORIE
  { id: 's16', name: 'Hummus', calories: '50', serving: 'per 2 tbsp', macros: '2g P / 4g C / 3g F', best_with: ['Vegetables', 'Chicken', 'Wraps', 'Pita'], flavor: ['Savory', 'Nutty', 'Creamy'], tier: 'Moderate' },
  { id: 's17', name: 'Guacamole', calories: '50', serving: 'per 2 tbsp', macros: '1g P / 2g C / 4g F', best_with: ['Mexican', 'Eggs', 'Wraps', 'Chicken'], flavor: ['Rich', 'Creamy', 'Fresh'], tier: 'Moderate' },
  { id: 's18', name: 'Tzatziki', calories: '35', serving: 'per 3 tbsp', macros: '2g P / 2g C / 2g F', best_with: ['Chicken', 'Lamb', 'Fish', 'Vegetables'], flavor: ['Creamy', 'Tangy', 'Fresh'], tier: 'Moderate' },
  { id: 's19', name: 'Pesto', calories: '70', serving: 'per 1 tbsp', macros: '2g P / 1g C / 7g F', best_with: ['Pasta', 'Chicken', 'Fish', 'Vegetables'], flavor: ['Herbal', 'Nutty', 'Rich'], tier: 'Moderate' },
  { id: 's20', name: 'Sugar-Free BBQ Sauce', calories: '15', serving: 'per 1 tbsp', macros: '0g P / 3g C / 0g F', best_with: ['Chicken', 'Ribs', 'Beef', 'Pulled Pork'], flavor: ['Smoky', 'Sweet', 'Tangy'], tier: 'Moderate' },
  { id: 's21', name: 'Buffalo Sauce', calories: '25', serving: 'per 2 tbsp', macros: '0g P / 0g C / 2g F', best_with: ['Chicken', 'Wings', 'Cauliflower', 'Fish'], flavor: ['Spicy', 'Tangy', 'Buttery'], tier: 'Moderate' },
  // HIGH PROTEIN (DIY)
  { id: 's22', name: 'Greek Yogurt Ranch', calories: '30', serving: 'per 2 tbsp', macros: '4g P / 1g C / 0g F', best_with: ['Salads', 'Chicken', 'Vegetables', 'Wraps'], flavor: ['Creamy', 'Herbal', 'Tangy'], tier: 'High Protein', recipe: 'Nonfat Greek yogurt + ranch seasoning + lemon juice + garlic powder. Thin with water for dressing.' },
  { id: 's23', name: 'Cottage Cheese Alfredo', calories: '60', serving: 'per 1/4 cup', macros: '10g P / 3g C / 2g F', best_with: ['Pasta', 'Chicken', 'Zucchini Noodles'], flavor: ['Creamy', 'Savory', 'Cheesy'], tier: 'High Protein', recipe: 'Blend cottage cheese + garlic + parmesan + pasta water until smooth. Heat and toss with pasta.' },
  { id: 's24', name: 'Greek Yogurt Caesar', calories: '35', serving: 'per 2 tbsp', macros: '4g P / 1g C / 1g F', best_with: ['Salads', 'Chicken', 'Fish', 'Wraps'], flavor: ['Savory', 'Tangy', 'Umami'], tier: 'High Protein', recipe: 'Greek yogurt + lemon juice + anchovy paste + garlic + parmesan + black pepper.' },
  { id: 's25', name: 'High Protein Marinara', calories: '80', serving: 'per 1/2 cup', macros: '10g P / 6g C / 2g F', best_with: ['Pasta', 'Zucchini Noodles', 'Meatballs', 'Chicken'], flavor: ['Rich', 'Savory', 'Italian'], tier: 'High Protein', recipe: 'Brown lean ground beef or turkey + add jarred marinara + Italian seasoning. Simmer 10 min.' },
];

export const SAUCE_TIERS = ['All', 'Zero Cal', 'Low Cal', 'Moderate', 'High Protein'];

export const SAUCE_TIER_COLORS = {
  'Zero Cal':    { bg: 'bg-emerald-100', text: 'text-emerald-700' },
  'Low Cal':     { bg: 'bg-blue-100',    text: 'text-blue-700' },
  'Moderate':    { bg: 'bg-amber-100',   text: 'text-amber-700' },
  'High Protein':{ bg: 'bg-purple-100',  text: 'text-purple-700' },
};

// ─── SEASONINGS ───────────────────────────────────────────────────────────────
export const SEASONINGS = [
  // EVERYDAY BASICS
  { id: 'garlic-pwd', name: 'Garlic Powder', cuisine: 'Basics', flavor: 'Savory, pungent', best_proteins: ['Chicken', 'Beef', 'Fish', 'Pork'], best_carbs: ['Potatoes', 'Rice', 'Pasta'], recipe_ideas: ['Season any protein', 'Add to sauces and marinades', 'Mix into ground meat'], pairs_with: ['Onion powder', 'Black pepper', 'Paprika'] },
  { id: 'onion-pwd', name: 'Onion Powder', cuisine: 'Basics', flavor: 'Sweet, savory', best_proteins: ['Chicken', 'Beef', 'Pork', 'Turkey'], best_carbs: ['Potatoes', 'Rice', 'Beans'], recipe_ideas: ['Season any protein', 'Add to soups and stews'], pairs_with: ['Garlic powder', 'Paprika', 'Cumin'] },
  { id: 'black-pepper', name: 'Black Pepper', cuisine: 'Basics', flavor: 'Spicy, sharp', best_proteins: ['Beef', 'Chicken', 'Fish', 'Eggs'], best_carbs: ['Potatoes', 'Pasta', 'Rice'], recipe_ideas: ['Season everything', 'Crust on steak'], pairs_with: ['Salt', 'Garlic powder'] },
  { id: 'sea-salt', name: 'Sea Salt / Kosher Salt', cuisine: 'Basics', flavor: 'Essential, clean', best_proteins: ['Everything'], best_carbs: ['Everything'], recipe_ideas: ['Season before cooking', 'Finish dishes'], pairs_with: ['Everything'] },
  { id: 'smoked-paprika', name: 'Smoked Paprika', cuisine: 'Basics', flavor: 'Smoky, sweet', best_proteins: ['Chicken', 'Beef', 'Pork', 'Shrimp'], best_carbs: ['Potatoes', 'Rice', 'Sweet potato'], recipe_ideas: ['Chicken rub', 'Add to chili', 'Season roasted veggies'], pairs_with: ['Cumin', 'Garlic powder', 'Cayenne'] },
  { id: 'sweet-paprika', name: 'Sweet Paprika', cuisine: 'Basics', flavor: 'Mild, sweet', best_proteins: ['Chicken', 'Eggs', 'Fish'], best_carbs: ['Potatoes', 'Pasta'], recipe_ideas: ['Deviled eggs', 'Hungarian stews', 'Chicken dishes'], pairs_with: ['Garlic powder', 'Onion powder'] },
  { id: 'cayenne', name: 'Cayenne Pepper', cuisine: 'Basics', flavor: 'Hot, sharp', best_proteins: ['Chicken', 'Beef', 'Shrimp', 'Eggs'], best_carbs: ['Potatoes', 'Rice', 'Beans'], recipe_ideas: ['Add heat to any dish', 'Buffalo-style', 'Spicy marinades'], pairs_with: ['Smoked paprika', 'Cumin', 'Garlic powder'] },
  { id: 'chili-powder', name: 'Chili Powder', cuisine: 'Basics', flavor: 'Earthy, mild heat', best_proteins: ['Beef', 'Chicken', 'Turkey', 'Pork'], best_carbs: ['Beans', 'Rice', 'Sweet potato'], recipe_ideas: ['Chili', 'Taco seasoning', 'BBQ rub'], pairs_with: ['Cumin', 'Garlic powder', 'Smoked paprika'] },
  { id: 'cumin', name: 'Cumin', cuisine: 'Basics', flavor: 'Earthy, warm', best_proteins: ['Beef', 'Chicken', 'Lamb', 'Turkey'], best_carbs: ['Rice', 'Beans', 'Lentils'], recipe_ideas: ['Mexican dishes', 'Middle Eastern', 'Indian curries', 'Taco meat'], pairs_with: ['Chili powder', 'Coriander', 'Garlic powder'] },
  { id: 'coriander', name: 'Coriander', cuisine: 'Basics', flavor: 'Citrusy, earthy', best_proteins: ['Chicken', 'Lamb', 'Fish'], best_carbs: ['Rice', 'Lentils', 'Potatoes'], recipe_ideas: ['Indian dishes', 'Middle Eastern', 'Marinades'], pairs_with: ['Cumin', 'Turmeric', 'Garlic powder'] },
  // MEDITERRANEAN
  { id: 'oregano', name: 'Oregano', cuisine: 'Mediterranean', flavor: 'Herbal, slightly bitter', best_proteins: ['Chicken', 'Fish', 'Lamb'], best_carbs: ['Pasta', 'Potatoes'], recipe_ideas: ['Italian seasoning', 'Greek chicken', 'Tomato-based sauces'], pairs_with: ['Basil', 'Thyme', 'Garlic powder'] },
  { id: 'basil', name: 'Basil', cuisine: 'Mediterranean', flavor: 'Sweet, fresh', best_proteins: ['Chicken', 'Fish', 'Shrimp'], best_carbs: ['Pasta', 'Tomatoes'], recipe_ideas: ['Caprese salad', 'Pesto', 'Italian dishes'], pairs_with: ['Oregano', 'Garlic', 'Tomato'] },
  { id: 'thyme', name: 'Thyme', cuisine: 'Mediterranean', flavor: 'Earthy, floral', best_proteins: ['Chicken', 'Lamb', 'Pork'], best_carbs: ['Potatoes', 'Beans'], recipe_ideas: ['Roasted chicken', 'Lemon thyme fish', 'Soups'], pairs_with: ['Rosemary', 'Oregano', 'Garlic'] },
  { id: 'rosemary', name: 'Rosemary', cuisine: 'Mediterranean', flavor: 'Piney, strong', best_proteins: ['Lamb', 'Chicken', 'Pork', 'Beef'], best_carbs: ['Potatoes', 'Bread'], recipe_ideas: ['Roasted potatoes', 'Lamb chops', 'Grilled chicken'], pairs_with: ['Thyme', 'Garlic', 'Lemon'] },
  { id: 'italian-blend', name: 'Italian Seasoning Blend', cuisine: 'Mediterranean', flavor: 'Herbal mix', best_proteins: ['Chicken', 'Fish', 'Ground beef'], best_carbs: ['Pasta', 'Bread', 'Tomatoes'], recipe_ideas: ['Season pasta sauce', 'Italian chicken', 'Homemade meatballs'], pairs_with: ['Garlic powder', 'Red pepper flakes'] },
  { id: 'zaatar', name: "Za'atar", cuisine: 'Mediterranean', flavor: 'Tangy, herbal', best_proteins: ['Chicken', 'Lamb', 'Fish'], best_carbs: ['Flatbread', 'Pita', 'Rice'], recipe_ideas: ['Za\'atar chicken', 'Fattoush dressing', 'Sprinkle on dips'], pairs_with: ['Sumac', 'Olive oil', 'Garlic'] },
  { id: 'sumac', name: 'Sumac', cuisine: 'Mediterranean', flavor: 'Tart, lemony', best_proteins: ['Chicken', 'Fish', 'Lamb'], best_carbs: ['Salads', 'Hummus', 'Rice'], recipe_ideas: ['Fattoush salad', 'Grilled chicken topping', 'Musakhan'], pairs_with: ["Za'atar", 'Olive oil', 'Onion'] },
  // MIDDLE EASTERN
  { id: 'baharat', name: 'Baharat (7 Spice)', cuisine: 'Middle Eastern', flavor: 'Warm, complex', best_proteins: ['Ground beef', 'Lamb', 'Chicken'], best_carbs: ['Rice', 'Bulgur'], recipe_ideas: ['Kofta kebab', 'Rice pilaf', 'Stuffed vegetables'], pairs_with: ['Allspice', 'Cinnamon', 'Cumin'] },
  { id: 'kabsa', name: 'Kabsa Spice', cuisine: 'Middle Eastern', flavor: 'Complex, aromatic', best_proteins: ['Chicken', 'Lamb', 'Beef'], best_carbs: ['Basmati rice'], recipe_ideas: ['Saudi Kabsa', 'Rice dishes', 'Slow-cooked meats'], pairs_with: ['Cardamom', 'Cinnamon', 'Black pepper'] },
  { id: 'ras-el-hanout', name: 'Ras el Hanout', cuisine: 'Middle Eastern', flavor: 'Complex, warm', best_proteins: ['Lamb', 'Chicken', 'Beef'], best_carbs: ['Couscous', 'Rice', 'Lentils'], recipe_ideas: ['Tagine', 'Moroccan chicken', 'Couscous dishes'], pairs_with: ['Cumin', 'Coriander', 'Cinnamon'] },
  { id: 'turmeric', name: 'Turmeric', cuisine: 'Middle Eastern', flavor: 'Earthy, slightly bitter', best_proteins: ['Chicken', 'Fish', 'Eggs'], best_carbs: ['Rice', 'Lentils', 'Potatoes'], recipe_ideas: ['Golden milk', 'Turmeric chicken', 'Anti-inflammatory rice'], pairs_with: ['Black pepper (increases absorption)', 'Ginger', 'Cumin'] },
  { id: 'cardamom', name: 'Cardamom', cuisine: 'Middle Eastern', flavor: 'Floral, sweet', best_proteins: ['Chicken', 'Lamb'], best_carbs: ['Rice', 'Oatmeal'], recipe_ideas: ['Arabic coffee', 'Rice pilaf', 'Chai spice blend'], pairs_with: ['Cinnamon', 'Ginger', 'Cloves'] },
  { id: 'cinnamon', name: 'Cinnamon', cuisine: 'Middle Eastern', flavor: 'Sweet, warm', best_proteins: ['Ground beef', 'Lamb'], best_carbs: ['Oatmeal', 'Sweet potato', 'Rice'], recipe_ideas: ['Moroccan beef', 'Oatmeal topping', 'Sweet potato seasoning'], pairs_with: ['Nutmeg', 'Cardamom', 'Allspice'] },
  // ASIAN
  { id: 'five-spice', name: 'Five Spice', cuisine: 'Asian', flavor: 'Complex, star anise forward', best_proteins: ['Pork', 'Duck', 'Chicken'], best_carbs: ['Rice', 'Noodles'], recipe_ideas: ['Char siu pork', 'Five spice chicken', 'Stir fry marinade'], pairs_with: ['Soy sauce', 'Ginger', 'Garlic'] },
  { id: 'ginger-pwd', name: 'Ginger Powder', cuisine: 'Asian', flavor: 'Spicy, warm', best_proteins: ['Chicken', 'Fish', 'Shrimp'], best_carbs: ['Rice', 'Stir fry vegetables'], recipe_ideas: ['Teriyaki marinade', 'Stir fry', 'Smoothies'], pairs_with: ['Garlic', 'Soy sauce', 'Sesame'] },
  { id: 'sesame', name: 'Sesame Seeds', cuisine: 'Asian', flavor: 'Nutty', best_proteins: ['Chicken', 'Fish', 'Tofu'], best_carbs: ['Rice', 'Noodles', 'Salads'], recipe_ideas: ['Garnish stir fry', 'Sesame chicken', 'Asian salads'], pairs_with: ['Soy sauce', 'Ginger', 'Garlic'] },
  { id: 'miso-pwd', name: 'Miso Powder', cuisine: 'Asian', flavor: 'Umami, salty', best_proteins: ['Fish', 'Chicken', 'Tofu'], best_carbs: ['Rice', 'Noodles', 'Vegetables'], recipe_ideas: ['Miso soup', 'Miso glaze', 'Umami marinade'], pairs_with: ['Ginger', 'Sesame', 'Soy sauce'] },
  // LATIN
  { id: 'sazon', name: 'Sazon', cuisine: 'Latin', flavor: 'Savory, earthy', best_proteins: ['Chicken', 'Ground beef', 'Pork'], best_carbs: ['Rice', 'Beans', 'Potatoes'], recipe_ideas: ['Yellow rice', 'Pernil', 'Beans and rice'], pairs_with: ['Adobo', 'Garlic powder', 'Cumin'] },
  { id: 'adobo', name: 'Adobo', cuisine: 'Latin', flavor: 'Garlicky, salty', best_proteins: ['Chicken', 'Pork', 'Beef', 'Fish'], best_carbs: ['Rice', 'Beans', 'Potatoes'], recipe_ideas: ['Season any protein', 'Puerto Rican chicken', 'Adobo marinade'], pairs_with: ['Sazon', 'Garlic powder', 'Oregano'] },
  { id: 'tajin', name: 'Tajin', cuisine: 'Latin', flavor: 'Chili, lime, salt', best_proteins: ['Chicken', 'Fish', 'Shrimp'], best_carbs: ['Fruit', 'Corn', 'Sweet potato'], recipe_ideas: ['Elotes (street corn)', 'Tajin chicken', 'Fruit topping'], pairs_with: ['Lime juice', 'Chili powder'] },
  // BBQ & AMERICAN
  { id: 'bbq-rub', name: 'BBQ Rub (sugar-free)', cuisine: 'BBQ', flavor: 'Smoky, sweet, savory', best_proteins: ['Ribs', 'Chicken', 'Brisket', 'Pork'], best_carbs: ['Potatoes', 'Corn'], recipe_ideas: ['Smoked brisket', 'BBQ chicken', 'Grilled ribs'], pairs_with: ['Smoked paprika', 'Cayenne', 'Black pepper'] },
  { id: 'montreal-steak', name: 'Montreal Steak Seasoning', cuisine: 'BBQ', flavor: 'Bold, peppery', best_proteins: ['Steak', 'Burgers', 'Pork'], best_carbs: ['Potatoes', 'Mushrooms'], recipe_ideas: ['Pan-seared steak', 'Burgers', 'Grilled salmon'], pairs_with: ['Garlic powder', 'Black pepper', 'Rosemary'] },
  { id: 'everything-bagel', name: 'Everything Bagel Seasoning', cuisine: 'BBQ', flavor: 'Savory, complex', best_proteins: ['Eggs', 'Chicken', 'Fish', 'Avocado toast'], best_carbs: ['Avocado', 'Potatoes', 'Bagels'], recipe_ideas: ['Scrambled eggs', 'Avocado toast', 'Roasted salmon'], pairs_with: ['Everything — versatile!'] },
  { id: 'lemon-pepper', name: 'Lemon Pepper', cuisine: 'BBQ', flavor: 'Bright, peppery', best_proteins: ['Fish', 'Chicken', 'Shrimp'], best_carbs: ['Pasta', 'Potatoes', 'Rice'], recipe_ideas: ['Lemon pepper chicken', 'Grilled fish', 'Pasta seasoning'], pairs_with: ['Garlic powder', 'Herbs'] },
  { id: 'ranch-seasoning', name: 'Ranch Seasoning', cuisine: 'BBQ', flavor: 'Herbal, savory', best_proteins: ['Chicken', 'Ground beef', 'Turkey'], best_carbs: ['Potatoes', 'Pasta', 'Vegetables'], recipe_ideas: ['Ranch dressing', 'Ranch chicken', 'Seasoned potatoes'], pairs_with: ['Garlic powder', 'Onion powder', 'Dill'] },
];

export const SEASONING_CUISINES = ['All', 'Basics', 'Mediterranean', 'Middle Eastern', 'Asian', 'Latin', 'BBQ'];

export const SEASONING_CUISINE_COLORS = {
  Basics:          { bg: 'bg-slate-100',  text: 'text-slate-700' },
  Mediterranean:   { bg: 'bg-blue-100',   text: 'text-blue-700' },
  'Middle Eastern':{ bg: 'bg-amber-100',  text: 'text-amber-700' },
  Asian:           { bg: 'bg-red-100',    text: 'text-red-700' },
  Latin:           { bg: 'bg-orange-100', text: 'text-orange-700' },
  BBQ:             { bg: 'bg-rose-100',   text: 'text-rose-700' },
};